---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(rvest)
library(xml2)
library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
```

Had to save the actual page as HTML as the exported CSV is not great...

```{r}
df <- xml2::read_html(x = "data/SearchResults.html") %>%
  html_node("table") %>%
  html_table() %>%
  `colnames<-`(., .[1, ]) %>%
  slice(-1)
```

```{r}
df %>%
  filter(Start != "Invalid Date" & Complete == "true") %>%
  mutate(date = str_sub(Start, 5, 24), 
         date = mdy_hms(date, tz = "PST")) %>%
  group_by(month = floor_date(date, unit = "month")) %>%
  summarize(completed = n()) %>%
  filter(month < as.POSIXct("2021-01-01") & month > as.POSIXct("2020-01-01")) %>%
  ggplot() +
  geom_line(aes(month, completed), size = 1, color= "#60d6f6") +
  geom_vline(aes(xintercept = as.integer(as.POSIXct("2020-12-01"))),
             col = "#f68060", alpha = 0.25, size = 5) +
  theme_minimal() +
  xlab(NULL) +
  ylab(NULL) +
  labs(title    = element_text("Completed Military Munitions Recognition and Safety Training 2020"),
       subtitle = element_text("Monthly bins, current month (December) highlighted in red"),
       caption  = element_text("Data source: www.fortordsafety.com"))
```

```{r}
df %>%
  mutate(Employer = str_to_upper(Employer),
         Employer = str_replace_all(Employer, "[[:punct:]]", ""),
         Employer = str_replace_all(Employer, "CONSTRUCTION", ""),
         Employer = str_trim(Employer, "both")) %>%
  filter(Employer != "NOCREDIT" & Employer != "TEST" & Employer != "" & Complete == "true") %>%
  group_by(Employer) %>%
  summarize(Count = n()) %>%
  arrange(desc(Count)) %>%
  top_n(10) %>%
  mutate(Employer= fct_reorder(Employer, Count)) %>%
  ggplot(aes(x = Employer, y = Count)) +
  geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) +
  theme_minimal() +
  xlab(NULL) +
  ylab(NULL) + 
  labs(title    = element_text("Most Common Employers"),
       subtitle = element_text("Top 10 based on completed trainings"),
       caption  = element_text("Data source: www.fortordsafety.com")) +
  coord_flip()
```

Group not viable due to the inconsistency of the data input.

Project based is the preference

Jurisdiction > Permits? > Track